### ISSUE TITLE
Wrong icons with 11.8.5

### ISSUE THREAD

**Issue by stefanofornari** [palexdev/VirtualizedFX#9]
Hi,
11.8.5 changes some icons:

![image](https://user-images.githubusercontent.com/43138/222888554-4b331ddc-447a-424d-ac2d-1666f90c1d0e.png)

With previous version:

![image](https://user-images.githubusercontent.com/43138/222889397-1259718d-d605-4ede-8f33-7410fc603adf.png)

**Comment by palexdev** [comment]
Update/Add [MFXResources](https://github.com/palexdev/MaterialFX/tree/rewrite/modules/resources) to the latest version on the classpath and use the new provided resources

**Comment by stefanofornari** [comment]
I knew II knew I had opened a similar issue, but I could not find it... Now I've got it. Please see https://github.com/palexdev/MFXResources/issues/1 it is the same thing. This bug should be filed in MaterialFX.

**Comment by palexdev** [comment]
Moved on palexdev/MaterialFX#209
